### ISSUE TITLE
may display one num when restart the game

### ISSUE THREAD

**Issue by LeoZ123** [gmc2777522/2048#2]
![image](https://cloud.githubusercontent.com/assets/22420842/24278530/bfe3f5e4-101a-11e7-820b-3569d30bb827.png)

**Comment by mengcheng-gong-intel** [comment]
display 2 num might be better : )

**Comment by LeoZ123** [comment]
@gmc2777522 i mean sometimes may display one num :(

**Comment by LeoZ123** [comment]
issue fixed
